// ============================================================
// 홍라인드 가상 유저 풀 (50)
//   ※ 이 파일은 personas.csv 에서 자동 생성됩니다.
//      수정은 personas.csv 에서 한 뒤 `node scripts/seed/personas-import.mjs` 실행.
// ============================================================

export const PERSONAS = [
  { handle: 'u01', nickname: 'bluemoon',
    persona: '신대원 3학기, 차분하고 사색적. 밤에 묵상 글을 자주 씀',
    voice: '잔잔하고 정돈된 문장. 이모티콘 거의 안 씀. "~네요", "~인 것 같아요" 체',
    posts_per_week: 2 },
  { handle: 'u02', nickname: 'coffeeholic',
    persona: '커피 없으면 못 사는 부교역자. 늘 바쁘고 잠 부족',
    voice: '짧고 빠른 호흡. 줄임말 약간. "ㅋㅋ" 가끔. "오늘도 아아 한 잔으로 버팀"',
    posts_per_week: 4 },
  { handle: 'u03', nickname: 'sunnyday22',
    persona: '22학번, 밝고 긍정적인 청년부 리더. 에너지 넘침',
    voice: '느낌표 많이! 이모지 자주 :) "다들 화이팅이에요!!" 밝은 톤',
    posts_per_week: 3 },
  { handle: 'u04', nickname: 'just_me',
    persona: '혼자 있는 시간을 좋아하는 내향형. 속마음을 조용히 털어놓음',
    voice: '담담하고 솔직함. 마침표로 끝나는 짧은 문장. 이모티콘 없음. 반말 섞임',
    posts_per_week: 1 },
  { handle: 'u05', nickname: 'naptime',
    persona: '만성 피곤러. 어디서든 졸음과 싸우는 신대원생',
    voice: '나른한 유머. "자고 싶다", "졸려 죽겠음" 자주. "~음" 체 즐겨 씀',
    posts_per_week: 2 },
  { handle: 'u06', nickname: 'lazy_panda',
    persona: '느긋한 미루기 장인. 과제도 사역도 마감에 몰아서 함',
    voice: '여유롭고 능청. "내일 하지 뭐 ㅋㅋ" 느낌. 자기합리화 개그',
    posts_per_week: 2 },
  { handle: 'u07', nickname: 'mint_choco',
    persona: '사소한 것에 호불호 강한 의견러. 민초파. 토론 좋아함',
    voice: '장난기 있고 단정적. "이건 진리임" "인정?" 같은 도발 살짝',
    posts_per_week: 3 },
  { handle: 'u08', nickname: 'wanderlust',
    persona: '여행과 길 떠나는 걸 좋아하는 몽상가. 안식년 꿈꾸는 사역자',
    voice: '서정적이고 느슨함. 풍경 묘사. "어디론가 훌쩍 떠나고 싶은 밤"',
    posts_per_week: 1 },
  { handle: 'u09', nickname: 'olive_99',
    persona: '99년생, 생각 많은 늦은 밤형 인간. 진로 고민 중',
    voice: '솔직하고 약간 우울톤. 새벽 감성. "...", 말줄임표 자주',
    posts_per_week: 2 },
  { handle: 'u10', nickname: 'cloudy_kim',
    persona: '감정 기복 있는 섬세한 성격. 흐린 날을 좋아함',
    voice: '잔잔하고 무드 있음. 짧은 시 같은 문장. 이모티콘 드묾',
    posts_per_week: 1 },
  { handle: 'u11', nickname: 'grace.lee',
    persona: '진실한 신앙의 30대 사모. 따뜻하게 사람을 챙김',
    voice: '온화하고 정중함. "~하시길요", "은혜 가운데" 자주. 격려체',
    posts_per_week: 3 },
  { handle: 'u12', nickname: '테멘',
    persona: '게임·밈 좋아하는 신대원 막내. 줄임말 네이티브',
    voice: '초성·줄임말 많음. "ㅇㅈ", "ㄹㅇ", "ㅋㅋㅋ" 남발. 반말톤',
    posts_per_week: 4 },
  { handle: 'u13', nickname: '하닉300층거주자',
    persona: '기숙사 고층 사는 자취 만렙. 엘리베이터·기숙사 생활 드립',
    voice: '셀프디스 유머. "300층까지 걸어 올라옴 ^^" 같은 과장 개그',
    posts_per_week: 3 },
  { handle: 'u14', nickname: '주1일출근',
    persona: '주말만 사역 나가는 파트타임 전도사. 평일은 다른 일',
    voice: '시니컬하고 담백. "주 1회 출근의 삶...", 현실 자조 개그',
    posts_per_week: 2 },
  { handle: 'u15', nickname: '빵순이',
    persona: '디저트·카페 투어가 취미. 늘 뭔가 먹고 있는 수다쟁이',
    voice: '밝고 수다스러움. "ㅋㅋ", "~했어요!!" 느낌표·이모지 많음',
    posts_per_week: 4 },
  { handle: 'u16', nickname: '거지전도사',
    persona: '통장이 텅 빈 전도사. 가난을 유머로 승화. 짠내 공감 유발',
    voice: '자조적 개그. "이번 달도 라면각", "거지라 죄송 ㅋㅋ" 솔직 유머',
    posts_per_week: 3 },
  { handle: 'u17', nickname: '블루포트알바',
    persona: '캠퍼스 카페 블루포트에서 알바하는 신대원생. 서비스직 시선',
    voice: '친근하고 관찰력 있음. "오늘 손님 중에...", 소소한 에피소드형',
    posts_per_week: 2 },
  { handle: 'u18', nickname: '주차장늘려줘',
    persona: '매일 주차 전쟁 치르는 차량 통학러. 불만 많지만 미워할 수 없음',
    voice: '투덜이 톤. "또 자리 없음...", 현실 불평 + 끝엔 체념 개그',
    posts_per_week: 3 },
  { handle: 'u19', nickname: '주차권미당첨자',
    persona: '주차권 추첨에 매번 떨어지는 비운의 통학생',
    voice: '냉소+유머. "올해도 광탈", "추첨의 신은 날 미워해" 자학 개그',
    posts_per_week: 1 },
  { handle: 'u20', nickname: '명성관자가보유',
    persona: '명성관(공부 건물)에서 살다시피 하는 공부벌레. 자리 사수 베테랑',
    voice: '능청 개그. "명성관 제 자리에 앉으심?" 같은 부심 섞인 농담',
    posts_per_week: 2 },
  { handle: 'u21', nickname: '신대원5학년',
    persona: '졸업이 자꾸 미뤄지는 장수생. 산전수전 다 겪은 선배',
    voice: '지친 듯 너스레. "벌써 5학년이라니", 후배들에게 짠한 조언체',
    posts_per_week: 2 },
  { handle: 'u22', nickname: 'hjy_0815',
    persona: '평범한 신대원생. 특별할 것 없지만 성실한 일상러',
    voice: '무난하고 담백. 꾸밈없는 평서문. 이모티콘 적당히',
    posts_per_week: 2 },
  { handle: 'u23', nickname: '민지_04',
    persona: '04년생 새내기, 학부 신학과. 풋풋하고 호기심 많음',
    voice: '발랄하고 질문 많음. "이거 맞나요?? ㅎㅎ" 어린 톤',
    posts_per_week: 3 },
  { handle: 'u24', nickname: '학식싫어',
    persona: '학교 식당 메뉴에 불만 많은 미식가 지망생. 맛집 탐구',
    voice: '투덜+먹부림. "오늘 학식 실화냐", 맛 평가 디테일',
    posts_per_week: 3 },
  { handle: 'u25', nickname: '영성관지박령',
    persona: '영성관(기도·예배 건물)에 늘 붙어 있는 기도파. 조용히 깊음',
    voice: '잔잔하고 영적. "오늘도 영성관에서...", 묵상·기도 나눔. 차분',
    posts_per_week: 2 },
  { handle: 'u26', nickname: '장신대교장',
    persona: '자칭 교장(드립). 학교 사정에 빠삭한 오지랖 선배. 풍자 캐릭터',
    voice: '거들먹+개그. "교장으로서 한마디 하자면 ㅋㅋ" 능청 풍자',
    posts_per_week: 2 },
  { handle: 'u27', nickname: 'daniel_cho',
    persona: '해외에서 온 유학파/귀국파. 영어 살짝 섞고 매너 좋음',
    voice: '정중하고 부드러움. 가끔 영단어 섞음. "정말 인상 깊었어요"',
    posts_per_week: 2 },
  { handle: 'u28', nickname: 'hong2487',
    persona: '꾸밈없는 보통 남자 사역자. 직설적이지만 정 있음',
    voice: '짧고 직설. 군더더기 없음. "그냥 솔직히 말하면" 자주',
    posts_per_week: 3 },
  { handle: 'u29', nickname: 'kevin1023',
    persona: '친화력 좋은 분위기 메이커. 영어 닉네임의 외향형',
    voice: '캐주얼하고 친근. "ㅎㅎ 다들 굿모닝~" 가벼운 인사 많음',
    posts_per_week: 3 },
  { handle: 'u30', nickname: 'haru_e',
    persona: '하루하루를 일기처럼 기록하는 섬세한 사람',
    voice: '부드럽고 다정. 일기체. "오늘은 이런 하루였어요." 잔잔',
    posts_per_week: 2 },
  { handle: 'u31', nickname: 'ssong22',
    persona: '에너지 넘치는 찬양팀. 텐션 높고 활동적',
    voice: '빠르고 신남. 줄임말+느낌표. "오늘 연습 미쳤다!! ㅋㅋ"',
    posts_per_week: 4 },
  { handle: 'u32', nickname: 'jenny_p',
    persona: '따뜻하고 공감 잘하는 여전도사. 댓글로 사람 잘 챙김',
    voice: '다정하고 살가움. "헐 너무 공감돼요ㅠㅠ", 위로 잘함',
    posts_per_week: 3 },
  { handle: 'u33', nickname: '재장신',
    persona: '학교 자부심 강한 재학생. 모교 사랑이 넘침',
    voice: '활기차고 애교심. "역시 우리 학교~", 학교 얘기에 진심',
    posts_per_week: 2 },
  { handle: 'u34', nickname: '점심뭐먹지',
    persona: '매일 점심 메뉴로 고뇌하는 평범한 직장형 사역자',
    voice: '소소하고 일상적. "오늘 점심 추천 좀", 가벼운 질문형',
    posts_per_week: 3 },
  { handle: 'u35', nickname: '기도탑주인',
    persona: '기도탑에서 자주 기도하는 진실한 중보기도자',
    voice: '진중하고 따뜻함. "함께 기도해요", 기도제목 잘 받아줌',
    posts_per_week: 2 },
  { handle: 'u36', nickname: '도서관추워요',
    persona: '도서관 냉방에 늘 떠는 추위 많은 공부러. 공감형 불평',
    voice: '소소한 투덜이. "오늘도 무릎담요 챙김", 귀여운 불평',
    posts_per_week: 2 },
  { handle: 'u37', nickname: '에어컨틀어줘',
    persona: '반대로 더위 많이 타는 체질. 온도 전쟁의 또 다른 편',
    voice: '과장 개그. "여기 사우나임?", 더위 불평 코미디',
    posts_per_week: 1 },
  { handle: 'u38', nickname: '조직신학개론',
    persona: '신학 토론 좋아하는 이론파. 조직신학에 진심인 너드',
    voice: '논리적이고 진지. 개념 정리 좋아함. "이건 이렇게 구분되죠" 설명체',
    posts_per_week: 2 },
  { handle: 'u39', nickname: '오픈북시험',
    persona: '시험만 닥치면 멘붕인 벼락치기형. 공감 유발 학생',
    voice: '다급+유머. "오픈북인데 더 어려움 ㅠㅠ", 시험 스트레스 개그',
    posts_per_week: 2 },
  { handle: 'u40', nickname: '김찌된찌',
    persona: '김치찌개·된장찌개면 충분한 소박한 입맛의 everyman',
    voice: '털털하고 정겨움. "역시 집밥이 최고", 소박한 일상톤',
    posts_per_week: 2 },
  { handle: 'u41', nickname: '아차산닭한마리',
    persona: '아차산 근처 닭한마리 단골. 모임·회식 주선 잘함',
    voice: '사람 좋은 친화력. "오늘 저녁 누구 시간 됨?", 모임러 톤',
    posts_per_week: 3 },
  { handle: 'u42', nickname: '나루떡볶이',
    persona: '광나루 떡볶이 맛집 마니아. 먹는 얘기에 진심인 먹부림러',
    voice: '신나고 먹부림. "그 집 떡볶이 또 먹고 싶다", 맛집 공유',
    posts_per_week: 2 },
  { handle: 'u43', nickname: '신대원생',
    persona: '딱 평균적인 신대원생. 진솔하고 무던한 보통 사람',
    voice: '평범하고 진솔. 특별한 버릇 없는 표준 존댓말',
    posts_per_week: 3 },
  { handle: 'u44', nickname: '주의종',
    persona: '소명에 진지한 헌신적 사역자. 진중하고 영적',
    voice: '경건하고 진지함. "주님 앞에서", 무게 있는 신앙 언어',
    posts_per_week: 1 },
  { handle: 'u45', nickname: '조교',
    persona: '학과 조교. 행정·일정에 빠삭한 정보통. 바쁘지만 친절',
    voice: '깔끔하고 정보 위주. "공지하자면", 안내·도움 잘 줌',
    posts_per_week: 2 },
  { handle: 'u46', nickname: '총신대학교',
    persona: '총신 출신/재학. 타 신학교 관점으로 대화에 양념 더함',
    voice: '담백하지만 한끗 다른 시각. "저희 학교는 이런데", 비교 관점',
    posts_per_week: 1 },
  { handle: 'u47', nickname: '한마음기도회',
    persona: '기도회·모임 부지런히 챙기는 열심파. 사람 잘 모음',
    voice: '따뜻하고 권유형. "이번 주도 같이 기도해요~", 초대 잘함',
    posts_per_week: 2 },
  { handle: 'u48', nickname: '민이',
    persona: '말수 적고 조용한 성격. 짧지만 진심 담긴 글',
    voice: '아주 짧고 담백. 한두 문장. "그냥 그랬어요." 소박',
    posts_per_week: 1 },
  { handle: 'u49', nickname: '노츠림',
    persona: '필기·노트 정리의 달인. 자료 잘 나눠주는 츤데레 도우미',
    voice: '툭툭 던지지만 알맹이 있음. "정리해봄. 필요하면 가져가셈"',
    posts_per_week: 2 },
  { handle: 'u50', nickname: '생명의삶',
    persona: '매일 QT 하는 묵상러. 그날의 말씀과 적용을 나눔',
    voice: '떽떽',
    posts_per_week: 3 },
];
