// ============================================================
// 홍라인드 시드 콘텐츠 (런칭 전 초기 글/댓글)
//   대상 게시판: 자유 · 사역고민 · 신학토론 · 설교준비 · 기도요청
//   (연봉/사역장터 제외)
//
//   seed.mjs 가 이 파일을 읽어 계정 → 글 → 댓글 순으로 적재한다.
//   분포: 자유 18 · 사역고민 16 · 기도요청 12 · 설교준비 8 · 신학토론 6 = 60글
//   daysAgo 는 0~27 로 흩뿌렸고, 댓글은 글과 같거나 더 최근(작은 daysAgo)으로 둠.
// ============================================================

// ── 1) 시드 계정 (20) ─────────────────────────────────────────
export const ACCOUNTS = [
  { handle: 'a01', nickname: '광야의소리',   affiliation: '미자립교회 담임' },
  { handle: 'a02', nickname: '새벽기도중독', affiliation: '부교역자' },
  { handle: 'a03', nickname: '신대원3학기',  affiliation: '신학대학원 재학' },
  { handle: 'a04', nickname: '시골목사',     affiliation: '농어촌 교회' },
  { handle: 'a05', nickname: '청년부담당',   affiliation: '교육전도사' },
  { handle: 'a06', nickname: '말씀묵상',     affiliation: '' },
  { handle: 'a07', nickname: '부목사5년차',  affiliation: '부목사' },
  { handle: 'a08', nickname: '전도사일기',   affiliation: '전도사' },
  { handle: 'a09', nickname: '갈릴리바람',   affiliation: '개척교회' },
  { handle: 'a10', nickname: '소명을품고',   affiliation: '신학대학원 재학' },
  { handle: 'a11', nickname: '강단아래',     affiliation: '부교역자' },
  { handle: 'a12', nickname: '산골밤하늘',   affiliation: '농어촌 교회' },
  { handle: 'a13', nickname: '찬양으로',     affiliation: '찬양사역자' },
  { handle: 'a14', nickname: '목양일념',     affiliation: '담임목사' },
  { handle: 'a15', nickname: '은혜아래',     affiliation: '' },
  { handle: 'a16', nickname: '새신자환영',   affiliation: '교육전도사' },
  { handle: 'a17', nickname: '늦깎이신학생', affiliation: '신학대학원 재학' },
  { handle: 'a18', nickname: '첫부임지',     affiliation: '전도사' },
  { handle: 'a19', nickname: '주중사역자',   affiliation: '선교단체 간사' },
  { handle: 'a20', nickname: '광야사십년',   affiliation: '원로목사' },
];

// ── 2) 글 (60) ───────────────────────────────────────────────
export const POSTS = [
  // ───── 자유 (18) ─────
  { key: 'p01', author: 'a05', category: '자유', daysAgo: 5,  atHour: 21, views: 53, likedBy: ['a13', 'a08'],
    title: '청년부 모임 끝나고 마시는 커피 한 잔이 낙이네요 ㅎㅎ',
    content: '오늘도 무사히 끝. 다들 한 주 고생 많으셨어요.' },
  { key: 'p02', author: 'a04', category: '자유', daysAgo: 1,  atHour: 20, views: 24,
    title: '시골 교회는 겨울 난방비가 진짜...',
    content: '예배당이 추워서 성도님들 무릎담요부터 챙겨 드리는 계절이 왔네요. 다들 따뜻하게 보내세요.' },
  { key: 'p03', author: 'a13', category: '자유', daysAgo: 12, atHour: 2,  views: 41, likedBy: ['a05'],
    title: '찬양 콘티 짜다 보니 새벽이네요 다들 안 주무세요?',
    content: '주일 콘티가 손에 안 잡혀서 붙들고 있다 보니 벌써 두 시... 새벽형 사역자분들 계신가요.' },
  { key: 'p04', author: 'a08', category: '자유', daysAgo: 8,  atHour: 18, views: 37, likedBy: ['a01', 'a06', 'a16'],
    title: '심방 다녀오는 길에 본 노을이 너무 예뻐서',
    content: '발걸음 무거웠는데 하늘 한 번 보고 다 풀렸어요. 사진은 못 찍었지만 마음에 남겨둡니다.' },
  { key: 'p05', author: 'a02', category: '자유', daysAgo: 15, atHour: 13, views: 66,
    title: '교역자 회의 길어질 때 버티는 본인만의 방법 있나요',
    content: '오늘 회의가 세 시간... 집중력 유지 비법 좀 나눠주세요 ㅎㅎ' },
  { key: 'p06', author: 'a15', category: '자유', daysAgo: 2,  atHour: 11, views: 29, likedBy: ['a05', 'a13', 'a08', 'a16'],
    title: '오늘 처음 가입했습니다, 반갑습니다',
    content: '여기저기 둘러보다 들어왔어요. 같은 길 걷는 분들 만나니 반갑네요. 잘 부탁드립니다.' },
  { key: 'p07', author: 'a19', category: '자유', daysAgo: 19, atHour: 22, views: 48,
    title: '주중에 사역하면 평일이 더 바쁜 거 저만 그런가요',
    content: '간사 사역이라 주중이 본게임인데, 주말엔 또 교회 섬기느라 쉬는 날이 사라졌어요 ㅠㅠ' },
  { key: 'p08', author: 'a09', category: '자유', daysAgo: 6,  atHour: 16, views: 72, likedBy: ['a14', 'a01', 'a04', 'a18'],
    title: '개척 1년차, 성도 세 가정이지만 오늘 한 분 더 오셨어요',
    content: '작은 일 같지만 저에겐 큰 사건입니다. 기뻐서 어디든 자랑하고 싶었어요.' },
  { key: 'p09', author: 'a06', category: '자유', daysAgo: 9,  atHour: 12, views: 33,
    title: '다들 점심 뭐 드세요... 교회 근처 혼밥 메뉴 추천받습니다',
    content: '월요일마다 혼자 점심인데 메뉴가 늘 고민이네요. 사역자 점심 루틴 궁금합니다.' },
  { key: 'p10', author: 'a11', category: '자유', daysAgo: 11, atHour: 17, views: 58, likedBy: ['a02', 'a07'],
    title: '설교 듣다가 운 적 있으세요? 오늘 동료 설교에 울컥했네요',
    content: '늘 강단에 서는 입장이라 잊고 있었는데, 오늘은 회중석에서 그냥 한참 울었습니다.' },
  { key: 'p11', author: 'a16', category: '자유', daysAgo: 4,  atHour: 15, views: 44, likedBy: ['a05', 'a08'],
    title: '주일학교 아이들이 그려준 그림 자랑하고 싶어서요',
    content: '"전도사님 사랑해요" 삐뚤빼뚤 적힌 글씨에 하루 종일 웃었습니다. 이 맛에 사역하죠.' },
  { key: 'p12', author: 'a03', category: '자유', daysAgo: 23, atHour: 23, views: 51, likedBy: ['a10', 'a07'],
    title: '신대원 시험기간... 헬라어 단어가 안 외워집니다 ㅠㅠ',
    content: '동사 변화표 앞에서 좌절 중입니다. 같이 헤매는 분 계시면 위로 좀...' },
  { key: 'p13', author: 'a14', category: '자유', daysAgo: 26, atHour: 9,  views: 80, likedBy: ['a01', 'a07', 'a11'],
    title: '20년 사역하고 처음으로 안식월을 받았습니다',
    content: '쉬는 법을 잊어버린 것 같아 어색하지만, 감사한 마음으로 한 달을 보내보려 합니다.' },
  { key: 'p14', author: 'a07', category: '자유', daysAgo: 14, atHour: 7,  views: 39,
    title: '운동 다시 시작했어요. 사역자도 체력이 영성이더라고요',
    content: '새벽기도 후 30분 걷기 시작했는데 마음까지 가벼워지네요. 다들 건강 챙기세요.' },
  { key: 'p15', author: 'a01', category: '자유', daysAgo: 7,  atHour: 10, views: 31,
    title: '교회 화단에 심은 상추가 자랐습니다 소소한 기쁨',
    content: '미자립이라 마당 한 켠에 텃밭 만들었는데, 첫 수확이네요. 다음 주 성도님들과 쌈 싸 먹기로 했어요.' },
  { key: 'p16', author: 'a18', category: '자유', daysAgo: 3,  atHour: 19, views: 27, likedBy: ['a04', 'a01'],
    title: '첫 부임지에서 맞는 첫 여름. 모든 게 낯설지만 설레네요',
    content: '아직 성도님 이름도 다 못 외웠지만, 하루하루 정 붙여가는 중입니다.' },
  { key: 'p17', author: 'a12', category: '자유', daysAgo: 17, atHour: 21, views: 35, likedBy: ['a04'],
    title: '산골 교회는 별이 잘 보여요. 밤 산책 추천합니다',
    content: '도시에선 못 보던 하늘이에요. 마음이 복잡할 때 한 바퀴 돌고 오면 정리가 됩니다.' },
  { key: 'p18', author: 'a20', category: '자유', daysAgo: 10, atHour: 8,  views: 63, likedBy: ['a08', 'a18', 'a03', 'a05'],
    title: '젊은 사역자들 보면 대견하고 부럽습니다. 응원해요',
    content: '내 젊을 적보다 훨씬 치열하게들 고민하시더군요. 먼저 걸어본 사람으로서 늘 응원합니다.' },

  // ───── 사역고민 (16) ─────
  { key: 'p19', author: 'a01', category: '사역고민', daysAgo: 21, atHour: 23, views: 142, likedBy: ['a02', 'a04', 'a06', 'a07'],
    title: '사역이 즐겁지 않을 때, 다들 어떻게 버티세요',
    content: '요즘 주일이 다가오면 설레기보다 무겁습니다. 소명은 분명한데 마음은 자꾸 메말라가요.\n비슷한 시기를 지나신 분들 어떻게 회복하셨는지 듣고 싶습니다.' },
  { key: 'p20', author: 'a07', category: '사역고민', daysAgo: 18, atHour: 14, views: 108, likedBy: ['a11', 'a08'],
    title: '담임목사님과 사역 방향이 안 맞을 때 어떻게 풀어가세요',
    content: '존경하는 분인데 방법론에서 자꾸 부딪힙니다. 부교역자로서 선을 어떻게 지켜야 할지 고민이에요.' },
  { key: 'p21', author: 'a05', category: '사역고민', daysAgo: 13, atHour: 22, views: 96, likedBy: ['a08', 'a16'],
    title: '청년들이 자꾸 교회를 떠납니다. 제 탓 같아서 힘드네요',
    content: '한 명 한 명 마음 쓰는데도 하나둘 발길이 줄어요. 제 부족함인 것 같아 밤마다 마음이 무겁습니다.' },
  { key: 'p22', author: 'a08', category: '사역고민', daysAgo: 25, atHour: 0,  views: 117, likedBy: ['a18', 'a09', 'a01'],
    title: '전도사 사역과 생계, 두 마리 토끼가 너무 버겁습니다',
    content: '사역은 사역대로 벅차고 생활은 생활대로 빠듯하네요. 이중직 하시는 분들 어떻게 균형 잡으세요.' },
  { key: 'p23', author: 'a02', category: '사역고민', daysAgo: 9,  atHour: 1,  views: 88, likedBy: ['a11'],
    title: '번아웃인 것 같은데 티를 못 내겠어요',
    content: '쉬어야 하는 걸 아는데 막상 멈추면 죄책감이 듭니다. 사역자가 지쳤다고 말해도 되는 걸까요.' },
  { key: 'p24', author: 'a11', category: '사역고민', daysAgo: 16, atHour: 6,  views: 74,
    title: '설교 준비할 절대 시간이 부족합니다 다들 어떻게...',
    content: '심방에 행정에 회의까지 하다 보면 토요일 밤이에요. 주중 설교 준비 루틴 좀 나눠주세요.' },
  { key: 'p25', author: 'a09', category: '사역고민', daysAgo: 6,  atHour: 23, views: 69, likedBy: ['a14', 'a01'],
    title: '개척 교회 성도 정체기, 조급함을 어떻게 다스리세요',
    content: '몇 달째 제자리인 것 같아 마음이 조급합니다. 머리로는 때를 기다려야 한다는 걸 아는데요.' },
  { key: 'p26', author: 'a16', category: '사역고민', daysAgo: 20, atHour: 13, views: 57,
    title: '주일학교 교사 모집이 매년 너무 힘듭니다',
    content: '헌신할 분을 구하기가 해마다 어려워져요. 교사 세우는 노하우 있으신 분 조언 부탁드립니다.' },
  { key: 'p27', author: 'a04', category: '사역고민', daysAgo: 24, atHour: 20, views: 91, likedBy: ['a20', 'a12', 'a01'],
    title: '고령화된 농어촌 교회, 다음 세대가 안 보입니다',
    content: '아이 울음소리가 끊긴 지 오래입니다. 그래도 이 자리를 지키는 의미를 다시 붙들고 싶어요.' },
  { key: 'p28', author: 'a18', category: '사역고민', daysAgo: 4,  atHour: 22, views: 46, likedBy: ['a04', 'a01'],
    title: '첫 부임지 적응이 생각보다 어렵네요 조언 구합니다',
    content: '의욕은 넘치는데 공동체 분위기를 읽는 게 쉽지 않아요. 선배님들 첫 사역지 어떻게 적응하셨나요.' },
  { key: 'p29', author: 'a19', category: '사역고민', daysAgo: 11, atHour: 21, views: 63,
    title: '사역과 가정 사이 균형, 정말 가능한 걸까요',
    content: '주말마다 가족과 시간을 못 가져요. 사명과 가정 둘 다 놓치고 싶지 않은데 늘 한쪽이 비네요.' },
  { key: 'p30', author: 'a14', category: '사역고민', daysAgo: 27, atHour: 9,  views: 79,
    title: '후임 양성, 어디서부터 시작해야 할지 모르겠습니다',
    content: '이제는 다음 세대 사역자를 키워야 할 때인데, 막상 무엇부터 손대야 할지 막막하네요.' },
  { key: 'p31', author: 'a06', category: '사역고민', daysAgo: 8,  atHour: 0,  views: 84, likedBy: ['a07', 'a09'],
    title: '비교의식이 자꾸 듭니다. 옆 교회 부흥 소식에 흔들려요',
    content: '내 자리에 감사하다가도 SNS 속 부흥 소식에 마음이 출렁입니다. 이 마음 어떻게 다스리세요.' },
  { key: 'p32', author: 'a13', category: '사역고민', daysAgo: 14, atHour: 16, views: 52,
    title: '찬양팀 내 갈등 중재가 너무 어렵습니다',
    content: '실력과 헌신, 세대 차이가 얽혀 매번 조율이 힘드네요. 팀 사역 오래 하신 분들 지혜 나눠주세요.' },
  { key: 'p33', author: 'a10', category: '사역고민', daysAgo: 2,  atHour: 18, views: 38, likedBy: ['a03'],
    title: '사역 현장과 신학교에서 배운 게 너무 달라 혼란스러워요',
    content: '실습 나가보니 교과서랑 현장이 딴 세상이네요. 이 간극을 어떻게 받아들여야 할까요.' },
  { key: 'p34', author: 'a07', category: '사역고민', daysAgo: 5,  atHour: 23, views: 71, likedBy: ['a11', 'a08'],
    title: '마음 상한 일로 사역이 흔들릴 때, 어떻게 회복하셨나요',
    content: '사람한테 받은 상처가 오래갑니다. 다시 사랑할 힘을 어디서 얻으시는지 듣고 싶어요.' },

  // ───── 기도요청 (12) ─────
  { key: 'p35', author: 'a02', category: '기도요청', daysAgo: 9,  atHour: 6,  prayedBy: ['a01', 'a04', 'a05', 'a06'],
    title: '담임목사님 건강을 위해 기도 부탁드립니다',
    content: '갑작스레 입원하셨습니다. 회복과 교회의 평안을 위해 함께 기도해 주세요.' },
  { key: 'p36', author: 'a08', category: '기도요청', daysAgo: 22, atHour: 5,  prayedBy: ['a01', 'a09', 'a18'],
    title: '재정이 막막합니다. 함께 기도해 주세요',
    content: '이번 달을 어떻게 넘길지 앞이 잘 안 보입니다. 그래도 공급하시는 주님을 신뢰하며 적습니다.' },
  { key: 'p37', author: 'a03', category: '기도요청', daysAgo: 16, atHour: 7,  prayedBy: ['a10', 'a17'],
    title: '신대원 졸업과 진로를 두고 기도 부탁드려요',
    content: '졸업이 다가오는데 부르심의 자리가 아직 안 보입니다. 조급하지 않게, 인도하심을 기다리도록.' },
  { key: 'p38', author: 'a09', category: '기도요청', daysAgo: 12, atHour: 8,  prayedBy: ['a01', 'a16', 'a14'],
    title: '개척 교회 첫 부활절, 새가족을 위해 기도해 주세요',
    content: '작은 교회의 첫 부활절입니다. 한 영혼이라도 주님 품에 안기도록 함께 기도해 주세요.' },
  { key: 'p39', author: 'a01', category: '기도요청', daysAgo: 3,  atHour: 5,  prayedBy: ['a06', 'a08', 'a02'],
    title: '지친 마음에 다시 첫사랑이 회복되도록',
    content: '사명은 그대로인데 가슴이 식은 것 같습니다. 처음 부르심의 감격을 회복하게 기도 부탁드려요.' },
  { key: 'p40', author: 'a16', category: '기도요청', daysAgo: 19, atHour: 10, prayedBy: ['a05', 'a13'],
    title: '여름성경학교 준비, 동역자와 재정을 위해',
    content: '교사도 예산도 빠듯한 상황에서 준비를 시작합니다. 아이들에게 복음이 온전히 전해지도록.' },
  { key: 'p41', author: 'a05', category: '기도요청', daysAgo: 7,  atHour: 22, prayedBy: ['a02', 'a09', 'a16', 'a08'], prayerAnswered: true,
    title: '[감사] 방황하던 청년 한 명이 돌아왔습니다!',
    content: '오래 마음에 품고 기도하던 청년이 어제 예배에 나왔어요. 같이 기뻐해 주세요. 하나님 감사합니다.' },
  { key: 'p42', author: 'a12', category: '기도요청', daysAgo: 14, atHour: 6,  prayedBy: ['a04', 'a01'],
    title: '홀로 사역하는 농어촌 목회자들을 위해',
    content: '동역자 없이 외로이 자리를 지키는 분들이 많습니다. 그분들의 영육간 강건함을 위해 함께 기도해요.' },
  { key: 'p43', author: 'a18', category: '기도요청', daysAgo: 25, atHour: 23, prayedBy: ['a04', 'a08', 'a06'],
    title: '부모님 구원을 위해 오래 기도 중입니다',
    content: '아직 믿지 않으시는 부모님이 주님을 만나시길 오래 기도하고 있어요. 함께 기억해 주시면 감사하겠습니다.' },
  { key: 'p44', author: 'a04', category: '기도요청', daysAgo: 2,  atHour: 6,  prayedBy: ['a06', 'a12'],
    title: '교회 어르신 한 분이 위독하십니다. 평안을 위해',
    content: '오래 교회를 지켜오신 권사님이 많이 편찮으십니다. 남은 시간 평안하시도록 기도 부탁드려요.' },
  { key: 'p45', author: 'a06', category: '기도요청', daysAgo: 6,  atHour: 9,  prayedBy: ['a05', 'a02'], prayerAnswered: true,
    title: '[감사] 수술받은 성도님이 어제 퇴원하셨어요',
    content: '많은 분들이 함께 기도해 주신 덕분입니다. 회복 잘 하시도록 끝까지 기억해 주세요. 감사합니다.' },
  { key: 'p46', author: 'a10', category: '기도요청', daysAgo: 10, atHour: 1,  prayedBy: ['a03', 'a17', 'a14'],
    title: '사명 앞에서 흔들리는 제 믿음을 위해 기도해 주세요',
    content: '부르심은 분명한데 제 자신이 자꾸 의심스럽습니다. 끝까지 붙드시는 손을 신뢰하도록 기도 부탁드려요.' },

  // ───── 설교준비 (8) ─────
  { key: 'p47', author: 'a06', category: '설교준비', daysAgo: 3,  atHour: 10, views: 61, likedBy: ['a03'], sermonVerse: '시편 23:1-4',
    title: '이번 주 본문 나눔 — 부족함이 없으리로다',
    content: '"여호와는 나의 목자시니" 이 한 문장을 붙들고 한 주를 준비하고 있습니다. 함께 묵상하실 분 있을까요.' },
  { key: 'p48', author: 'a14', category: '설교준비', daysAgo: 15, atHour: 11, views: 73, likedBy: ['a11', 'a01'], sermonVerse: '누가복음 15:25-32',
    title: '탕자 비유, 큰아들에 초점 둔 설교 해보신 분',
    content: '늘 둘째 아들 중심으로 전했는데, 올해는 큰아들의 마음을 다뤄보려 합니다. 경험 나눠주실 분.' },
  { key: 'p49', author: 'a11', category: '설교준비', daysAgo: 20, atHour: 15, views: 55, sermonVerse: '마태복음 5:1-12',
    title: '산상수훈 팔복 시리즈, 몇 주에 나눠 하세요?',
    content: '한 주에 다 다루기엔 벅차고, 너무 길어지면 흐름이 끊길까 고민입니다. 시리즈 구성 조언 부탁드려요.' },
  { key: 'p50', author: 'a01', category: '설교준비', daysAgo: 11, atHour: 23, views: 68, likedBy: ['a07', 'a14'], sermonVerse: '이사야 53:3-6',
    title: '고난주간 설교, 매년 새롭게 풀기가 어렵습니다',
    content: '같은 본문을 해마다 전하다 보니 저부터 익숙해져서요. 신선하게 다가가는 노하우가 있을까요.' },
  { key: 'p51', author: 'a07', category: '설교준비', daysAgo: 8,  atHour: 14, views: 47, sermonVerse: '요한복음 1:14',
    title: "요한복음 서문 '말씀이 육신이 되어' 어떻게 전하세요",
    content: '성육신의 신비를 회중이 체감하도록 전하고 싶은데, 추상적으로 흐르기 쉬워 고민입니다.' },
  { key: 'p52', author: 'a20', category: '설교준비', daysAgo: 24, atHour: 8,  views: 59, likedBy: ['a06'], sermonVerse: '전도서 3:1-11',
    title: '전도서, 허무를 넘어 소망으로 잇는 흐름 고민 중',
    content: '"헛되다"는 외침에서 멈추지 않고 하나님 안의 의미로 잇고 싶은데, 본문 배치를 어떻게 하면 좋을까요.' },
  { key: 'p53', author: 'a13', category: '설교준비', daysAgo: 5,  atHour: 17, views: 42,
    title: '찬양과 설교 본문을 맞추는 편이세요?',
    content: '예배 흐름상 콘티와 설교 본문을 연결하면 좋다는데, 다들 얼마나 신경 쓰시는지 궁금합니다.' },
  { key: 'p54', author: 'a02', category: '설교준비', daysAgo: 17, atHour: 12, views: 64, likedBy: ['a16', 'a13'], sermonVerse: '요한복음 6:1-13',
    title: '오병이어, 아이의 도시락에 초점 둔 적 있어요',
    content: '작은 헌신이 어떻게 쓰임받는지 아이의 시선으로 풀었더니 반응이 좋았습니다. 같은 시도 해보실 분.' },

  // ───── 신학토론 (6) ─────
  { key: 'p55', author: 'a03', category: '신학토론', daysAgo: 17, atHour: 14, views: 88, likedBy: ['a06'],
    title: '칭의와 성화, 설교에서 어디까지 구분해서 전하시나요',
    content: '학교에선 구분이 명확한데 막상 성도들 앞에선 뭉뚱그리게 되더라고요. 현장에서 어떻게 풀어 전하시는지.' },
  { key: 'p56', author: 'a10', category: '신학토론', daysAgo: 22, atHour: 20, views: 76,
    title: '예정론, 성도들에게 어떻게 설명하세요',
    content: '오해 없이 위로의 교리로 전하고 싶은데, 자칫 운명론처럼 들릴까 늘 조심스럽습니다.' },
  { key: 'p57', author: 'a17', category: '신학토론', daysAgo: 10, atHour: 21, views: 54,
    title: '종말론 입장 차이, 목회 현장에서 어떻게 다루세요',
    content: '교단·신학교마다 강조점이 달라서요. 회중 안에 다양한 입장이 섞여 있을 때 균형을 어떻게 잡으시나요.' },
  { key: 'p58', author: 'a06', category: '신학토론', daysAgo: 26, atHour: 0,  views: 61,
    title: '구약의 전쟁 본문을 회중에게 어떻게 설교하세요',
    content: '진멸 명령 같은 본문 앞에서 늘 조심스럽습니다. 하나님의 성품과 어떻게 연결해 전하시는지 궁금해요.' },
  { key: 'p59', author: 'a14', category: '신학토론', daysAgo: 13, atHour: 9,  views: 58,
    title: '세대주의 vs 언약신학, 설교에 영향 주나요',
    content: '신학적 틀이 본문 적용에 알게 모르게 작용하는 것 같아요. 다들 어느 쪽에 서서 강단에 서시는지.' },
  { key: 'p60', author: 'a03', category: '신학토론', daysAgo: 6,  atHour: 23, views: 49, likedBy: ['a10'],
    title: '방언과 신유, 신학교와 교회 현장의 간극',
    content: '배운 것과 실제 신앙 현장의 온도차가 큽니다. 이 주제를 균형 있게 정리하신 분 계실까요.' },
];

// ── 3) 댓글 / 대댓글 ─────────────────────────────────────────
//   (모든 글에 달지 않음 — 댓글 0인 글이 자연스럽다)
export const COMMENTS = [
  // 사역고민
  { post: 'p19', author: 'a04', daysAgo: 21, atHour: 23, key: 'c01',
    content: '저도 그 시기 지났어요. 무리해서 채우려 하지 말고 한 주는 그냥 쉬어가도 괜찮더라고요.' },
  { post: 'p19', author: 'a01', daysAgo: 20, atHour: 7, replyTo: 'c01',
    content: '그 말씀이 위로가 되네요. 감사합니다.' },
  { post: 'p19', author: 'a06', daysAgo: 20, atHour: 9,
    content: '같이 기도하겠습니다. 혼자 아니에요.' },
  { post: 'p19', author: 'a07', daysAgo: 19, atHour: 6,
    content: '저는 사역일지를 다시 쓰기 시작하면서 회복됐어요. 작은 감사부터 적어보세요.' },
  { post: 'p20', author: 'a14', daysAgo: 18, atHour: 15, key: 'c05',
    content: '담임 입장에서도 말 못 할 고민이 있을 수 있어요. 차 한잔 청해 솔직히 여쭤보세요.' },
  { post: 'p20', author: 'a02', daysAgo: 17, atHour: 8, replyTo: 'c05',
    content: '방법보다 신뢰가 먼저 쌓이면 대화가 열리더라고요. 응원합니다.' },
  { post: 'p21', author: 'a05', daysAgo: 13, atHour: 23,
    content: '청년 사역은 숫자보다 한 명이라는 말 붙들고 가요. 떠난 것도 하나님 손에 있습니다.' },
  { post: 'p21', author: 'a08', daysAgo: 12, atHour: 7,
    content: '제 탓이라 자책 마세요. 그 마음 자체가 이미 사랑인걸요.' },
  { post: 'p22', author: 'a18', daysAgo: 24, atHour: 22,
    content: '이중직 고민 정말 공감합니다. 혼자가 아니에요, 같이 버텨요.' },
  { post: 'p22', author: 'a09', daysAgo: 23, atHour: 6,
    content: '저도 비슷한 자리라 댓글 답니다. 현실과 소명 사이에서 오늘도 기도하네요.' },
  { post: 'p23', author: 'a11', daysAgo: 9, atHour: 8,
    content: '번아웃 티 내도 괜찮아요. 오히려 솔직히 말했더니 동료들이 도와줬습니다.' },
  { post: 'p23', author: 'a06', daysAgo: 8, atHour: 23,
    content: '쉼도 사역입니다. 자신을 먼저 돌보세요.' },
  { post: 'p25', author: 'a14', daysAgo: 6, atHour: 23,
    content: '개척 정체기 안 겪은 목회자 없습니다. 지금은 씨 뿌리는 계절이에요.' },
  { post: 'p27', author: 'a20', daysAgo: 23, atHour: 21, key: 'c14',
    content: '농어촌 목회 오래 했습니다. 다음 세대는 우리가 못 봐도 주님이 이으십니다.' },
  { post: 'p27', author: 'a12', daysAgo: 22, atHour: 20, replyTo: 'c14',
    content: '같은 산골이라 더 와닿네요. 힘내세요 목사님.' },
  { post: 'p28', author: 'a04', daysAgo: 4, atHour: 23,
    content: '첫 부임지 다 그래요. 1년만 지나면 보입니다. 조급해 마세요.' },
  { post: 'p28', author: 'a01', daysAgo: 3, atHour: 7,
    content: '성도 한 분 한 분 이름 외우는 것부터 시작해보세요. 응원합니다.' },
  { post: 'p31', author: 'a07', daysAgo: 8, atHour: 1,
    content: '비교는 사역자의 영원한 숙제죠. 저도 오늘 또 졌습니다 ㅎㅎ' },
  { post: 'p31', author: 'a14', daysAgo: 7, atHour: 9,
    content: '옆 교회 부흥도 주님 일, 우리 교회 작음도 주님 일. 같은 밭이에요.' },
  { post: 'p33', author: 'a17', daysAgo: 2, atHour: 19,
    content: '저도 신대원 다니며 같은 혼란 겪는 중이라 반갑네요(?).' },
  { post: 'p33', author: 'a02', daysAgo: 1, atHour: 12,
    content: '현장이 교과서랑 다른 게 정상이에요. 신학이 현장에서 익어가더라고요.' },
  { post: 'p34', author: 'a01', daysAgo: 5, atHour: 23,
    content: '사람에게 받은 상처는 결국 주님 앞에서만 풀리더라고요. 함께 기도할게요.' },

  // 기도요청
  { post: 'p35', author: 'a05', daysAgo: 9, atHour: 8,
    content: '함께 기도합니다. 속히 회복되시길.' },
  { post: 'p35', author: 'a06', daysAgo: 8, atHour: 22,
    content: '주님이 붙드실 줄 믿습니다.' },
  { post: 'p36', author: 'a01', daysAgo: 22, atHour: 9,
    content: '재정의 광야, 같이 기도할게요. 때를 따라 만나를 주실 거예요.' },
  { post: 'p38', author: 'a16', daysAgo: 12, atHour: 10,
    content: '첫 부활절 축하드려요! 새가족을 위해 기도합니다.' },
  { post: 'p39', author: 'a08', daysAgo: 3, atHour: 8,
    content: '첫사랑 회복, 저에게도 필요한 기도였어요. 함께해요.' },
  { post: 'p41', author: 'a02', daysAgo: 7, atHour: 23, key: 'c27',
    content: '할렐루야! 한 영혼이 돌아온 소식에 같이 기쁩니다.' },
  { post: 'p41', author: 'a09', daysAgo: 6, atHour: 7, replyTo: 'c27',
    content: '이런 소식이 정말 힘이 되네요. 축하해요!' },
  { post: 'p43', author: 'a04', daysAgo: 24, atHour: 7,
    content: '부모님 구원, 끝까지 포기 마세요. 저희 어머니도 오랜 기도 끝에 주님 만나셨어요.' },
  { post: 'p44', author: 'a06', daysAgo: 2, atHour: 9,
    content: '남은 시간 평안하시도록 함께 기도합니다.' },
  { post: 'p45', author: 'a05', daysAgo: 6, atHour: 12,
    content: '퇴원 소식 너무 감사해요! 함께 감사드립니다.' },
  { post: 'p46', author: 'a14', daysAgo: 10, atHour: 8,
    content: '흔들림조차 주님이 붙드시는 과정이에요. 기도하겠습니다.' },

  // 설교준비
  { post: 'p47', author: 'a03', daysAgo: 3, atHour: 12,
    content: "저도 같은 본문이라 반갑네요. 4절 '해를 두려워하지 않을 것은'에서 오래 머물게 됩니다." },
  { post: 'p48', author: 'a11', daysAgo: 15, atHour: 13, key: 'c34',
    content: '큰아들 관점 설교 강력 추천이에요. 의외로 회중 반응이 뜨겁습니다.' },
  { post: 'p48', author: 'a01', daysAgo: 14, atHour: 9, replyTo: 'c34',
    content: '오 좋은 팁 감사합니다. 한번 시도해볼게요.' },
  { post: 'p49', author: 'a07', daysAgo: 20, atHour: 16,
    content: '저는 8주로 나눠서 했어요. 한 복마다 한 주씩 충분히 다루니 좋더라고요.' },
  { post: 'p50', author: 'a20', daysAgo: 11, atHour: 23,
    content: '고난주간은 본문을 바꾸기보다 시선을 바꿔보세요. 매년 새로워집니다.' },
  { post: 'p54', author: 'a13', daysAgo: 17, atHour: 13,
    content: '오병이어, 아이 도시락 관점 주일학교에서도 정말 좋아했어요.' },

  // 신학토론
  { post: 'p55', author: 'a06', daysAgo: 17, atHour: 15, key: 'c39',
    content: '저는 칭의는 선언, 성화는 동행으로 단순화해서 전합니다.' },
  { post: 'p55', author: 'a14', daysAgo: 16, atHour: 8, replyTo: 'c39',
    content: '구분은 하되 분리하지 않는다 — 이 톤이면 회중이 덜 헷갈리더라고요.' },
  { post: 'p56', author: 'a17', daysAgo: 21, atHour: 22,
    content: '예정론은 위로의 교리로 접근하면 거부감이 확실히 덜해요.' },
  { post: 'p57', author: 'a14', daysAgo: 10, atHour: 22,
    content: "종말론은 입장보다 '깨어 있으라'는 적용에 무게를 두는 편이에요." },
  { post: 'p59', author: 'a10', daysAgo: 13, atHour: 10,
    content: '언약신학 쪽인데 설교 흐름엔 분명 영향을 주는 것 같아요.' },

  // 자유
  { post: 'p06', author: 'a05', daysAgo: 2, atHour: 12,
    content: '환영합니다! 은혜 가운데 교제해요.' },
  { post: 'p06', author: 'a13', daysAgo: 1, atHour: 18,
    content: '반가워요 :) 자주 뵈어요.' },
  { post: 'p08', author: 'a14', daysAgo: 6, atHour: 18,
    content: '한 분의 무게가 얼마나 큰지 알죠. 진심으로 축하합니다.' },
  { post: 'p10', author: 'a02', daysAgo: 11, atHour: 19,
    content: '동료 설교에 우는 거, 참 건강한 마음이에요.' },
  { post: 'p12', author: 'a10', daysAgo: 23, atHour: 23, key: 'c48',
    content: '헬라어 단어장 붙들고 같이 울고 있습니다 ㅋㅋ 화이팅이에요.' },
  { post: 'p12', author: 'a07', daysAgo: 22, atHour: 7, replyTo: 'c48',
    content: '지나고 보면 그 고생이 평생 자산이에요. 버텨요!' },
  { post: 'p13', author: 'a01', daysAgo: 25, atHour: 10,
    content: '20년 만의 안식월이라니, 정말 축하드립니다. 이번엔 꼭 푹 쉬세요.' },
  { post: 'p18', author: 'a08', daysAgo: 10, atHour: 9,
    content: '선배님 말씀에 힘이 납니다. 감사해요.' },
];
